-- EXERCICIO 1

SELECT P.IDPRODUTO, P.NOME
FROM PRODUTO P WHERE P.IDPRODUTO != ALL( 
  SELECT P.IDPRODUTO FROM PRODUTO P
  INNER JOIN PEDIDOITEM PI
  ON P.IDPRODUTO = PI.IDPRODUTO
  INNER JOIN PEDIDO PE
  ON PE.IDPEDIDO = PI.IDPEDIDO
  WHERE PE.DATAPEDIDO >  ADD_MONTHS(TRUNC(SYSDATE), -4)
)

-- EXERCICIO 2

CREATE VIEW ProdutoNaoVendidoQuatroMeses AS
  SELECT P.IDPRODUTO, P.NOME
      FROM PRODUTO P WHERE P.IDPRODUTO != ALL( 
        SELECT P.IDPRODUTO FROM PRODUTO P
        INNER JOIN PEDIDOITEM PI
        ON P.IDPRODUTO = PI.IDPRODUTO
        INNER JOIN PEDIDO PE
        ON PE.IDPEDIDO = PI.IDPEDIDO
        WHERE PE.DATAPEDIDO >  ADD_MONTHS(TRUNC(SYSDATE), -4)
  );
  
UPDATE PRODUTO SET PRODUTO.SITUACAO = 'I' WHERE PRODUTO.IDPRODUTO = ANY(SELECT P4.IDPRODUTO FROM PRODUTONAOVENDIDOQUATROMESES P4);

-- exercicio 3

SELECT COUNT( PI.IDPEDIDOITEM)
	FROM PEDIDOITEM PI
	INNER JOIN PEDIDO PE
	ON PI.IDPEDIDO = PE.IDPEDIDO
	WHERE PI.IDPRODUTO = :PRODUTOID
	AND PE.DATAPEDIDO > TO_DATE('2017/01/01','yyyy/mm/dd')