-- EXERCICIO 1

SELECT P.IDPRODUTO, P.NOME
FROM PRODUTO P WHERE P.IDPRODUTO != ALL( 
  SELECT P.IDPRODUTO FROM PRODUTO P
  INNER JOIN PEDIDOITEM PI
  ON P.IDPRODUTO = PI.IDPRODUTO
  INNER JOIN PEDIDO PE
  ON PE.IDPEDIDO = PI.IDPEDIDO
  WHERE PE.DATAPEDIDO >  ADD_MONTHS(TRUNC(SYSDATE), -4)
)

SELECT * FROM PRODUTO
-- EXERCICIO 2

UPDATE PRODUTO SET PRODUTO.SITUACAO = 'I' WHERE(
    SELECT P.IDPRODUTO, P.NOME
      FROM PRODUTO P WHERE P.IDPRODUTO != ALL( 
        SELECT P.IDPRODUTO FROM PRODUTO P
        INNER JOIN PEDIDOITEM PI
        ON P.IDPRODUTO = PI.IDPRODUTO
        INNER JOIN PEDIDO PE
        ON PE.IDPEDIDO = PI.IDPEDIDO
        WHERE PE.DATAPEDIDO >  ADD_MONTHS(TRUNC(SYSDATE), -4)
    )
)
