CREATE TABLE USUARIOS(
IDUSUARIO NUMBER(12) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL, 
SENHA VARCHAR2(100) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
SEXO CHAR(1) NOT NULL,
CONSTRAINT PK_USUARIO PRIMARY KEY(IDUSUARIO));

CREATE TABLE AMIZADES(
IDAMIZADES NUMBER(12) NOT NULL,
IDUSUARIO NUMBER(12) NOT NULL, 
IDAMIGO NUMBER(12) NOT NULL,
CONSTRAINT PK_AMIZADES PRIMARY KEY(IDAMIZADES),
CONSTRAINT FK_USUARIO FOREIGN KEY(IDUSUARIO) REFERENCES USUARIOS,
CONSTRAINT FK_AMIGO FOREIGN KEY(IDAMIGO) REFERENCES USUARIOS);

CREATE TABLE SOLICITACAO(
IDSOLICITACAO NUMBER(12) NOT NULL,
IDSOLICITANTE NUMBER(12) NOT NULL, 
IDSOLICITADO NUMBER(12) NOT NULL,
SITUACAO CHAR(1) NOT NULL,
CONSTRAINT PK_SOLICITACAO PRIMARY KEY(IDSOLICITACAO),
CONSTRAINT FK_SOLICITANTE FOREIGN KEY(IDSOLICITANTE) REFERENCES USUARIOS,
CONSTRAINT FK_SOLICITADO FOREIGN KEY(IDSOLICITADO) REFERENCES USUARIOS);

CREATE TABLE POSTAGENS(
IDPOSTAGEM NUMBER(12) NOT NULL,
TEXTO VARCHAR2(500) NOT NULL,
URLIMAGEM VARCHAR2(300),
DATAPOSTAGEM DATE NOT NULL,
IDCURTIDA NUMBER(12),
CONSTRAINT PK_IDPOSTAGEM PRIMARY KEY (IDPOSTAGEM));

CREATE TABLE CURTIDAS(
IDCURTIDA NUMBER(12) NOT NULL,
IDPOSTAGEM NUMBER(12) NOT NULL,
IDUSUARIO NUMBER(12) NOT NULL,
CONSTRAINT PK_CURTIDA PRIMARY KEY(IDCURTIDA));

ALTER TABLE POSTAGENS ADD CONSTRAINT FK_CURTIDA FOREIGN KEY (IDCURTIDA) REFERENCES CURTIDAS(IDCURTIDA);

ALTER TABLE CURTIDAS ADD CONSTRAINT FK_IDPOSTAGEMCURTIDA FOREIGN KEY (IDPOSTAGEM) REFERENCES POSTAGENS(IDPOSTAGEM);
ALTER TABLE CURTIDAS ADD CONSTRAINT FK_IDUSUARIOCURTIDOR FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO);


INSERT INTO USUARIOS(IDUSUARIO, EMAIL, SENHA, NOME, DATANASCIMENTO, SEXO)
VALUES(1,'WILLIAM.FERNANDO92@GMAIL.COM','123456','WILLIAM',TO_DATE('06-04-1996', 'DD-MM-YYYY'),'M');
INSERT INTO USUARIOS(IDUSUARIO, EMAIL, SENHA, NOME, DATANASCIMENTO, SEXO)
VALUES(2,'ALEXIA@GMAIL.COM','123456','ALEXIA',TO_DATE('14-02-2000', 'DD-MM-YYYY'),'F');
INSERT INTO USUARIOS(IDUSUARIO, EMAIL, SENHA, NOME, DATANASCIMENTO, SEXO)
VALUES(3,'ALANA@GMAIL.COM','123456','ALANA',TO_DATE('27-06-1999', 'DD-MM-YYYY'),'F');
INSERT INTO USUARIOS(IDUSUARIO, EMAIL, SENHA, NOME, DATANASCIMENTO, SEXO)
VALUES(4,'DEORDINES@GMAIL.COM','123456','DEORDINES',TO_DATE('18-08-1993', 'DD-MM-YYYY'),'M');
INSERT INTO USUARIOS(IDUSUARIO, EMAIL, SENHA, NOME, DATANASCIMENTO, SEXO)
VALUES(5,'MIRELLA@GMAIL.COM','123456','MIRELLA',TO_DATE('10-05-1994', 'DD-MM-YYYY'),'F');



CREATE SEQUENCE SQ_AMIZADES  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;
	
CREATE SEQUENCE SQ_SOLICITACAO  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;

CREATE SEQUENCE SQ_POSTAGENS
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;

CREATE SEQUENCE SQ_USUARIO
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;
	
CREATE SEQUENCE SQ_CURTIDAS  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;